Modified protocol mqtt module based on requirements
sale3/iot-gateway-app pull request #101
Opened 2024-08-30 11:30 UTC by novicatepic

Had to put everything into this one commit because I waited for a long time for the first PR approval, so couldn't really do it as it was supposed to be done.

2024-09-04 07:37 UTC, sale3 commented
PR description is not saying anything about changes in the PR, please update it.

2024-09-04 07:41 UTC, sale3 requested changes

2024-09-04 07:41 UTC, sale3 commented on src/protocol_mqtt.py
There are functions (`update_protocols_on_startup`,  `get_current_protocol_ids`, `get_data_by_can_id`) that are not related to mqtt, so you might consider changing the module name or moving those functions to another module.
You can consider moving them to the new class that should be created instead of data tuple mentioned in the other PR.

2024-09-05 07:59 UTC, novicatepic commented on src/protocol_mqtt.py
I renamed module name, if there is a lot of code in the future I will make separate modules.

2024-09-06 07:29 UTC, sale3 requested changes

2024-09-06 07:29 UTC, sale3 commented on src/can_protocol.py
> +    protocol_ids_formatted = {
No need to send IDs, change this to send a basic request that will trigger sync mechanism on cloud.

2024-09-09 07:41 UTC, sale3 approved these changes

2024-09-09 07:42 UTC, merged