35 restmqtt update gateway processes to respond to configuration change and to use mqtt clients
sale3/iot-gateway-app pull request #37
Opened 2024-02-12 14:18 UTC by stekap000

MQTT clients are added to processes (one for each process since that is the way that original code handled mqtt on sensor side).
Additional MQTT client in added in main for final stats_service data.
Function calls to data_service functions are modified to accept additional parameters (username and gateway-cloud broker client).

2024-02-26 09:30 UTC, CodeBojan approved these changes

2024-02-26 09:31 UTC, CodeBojan submitted a review, later dismissed

2024-02-26 09:55 UTC, CodeBojan approved these changes

2024-02-27 09:42 UTC, sergiPopescou requested changes

2024-02-27 10:05 UTC, stekap000 commented on src/app.py
>  import json
Ne koristi se, dio je originalnog koda. Uklonjeno je.

2024-02-27 10:05 UTC, stekap000 commented on src/app.py
> +from mqtt_util import *
Promijenjeno.

2024-02-27 10:06 UTC, stekap000 commented on src/app.py
>  from multiprocessing import Process, Queue, Event
Koristi se u main funkciji. Isto je dio originalnog koda.

2024-02-27 12:36 UTC, sale3 commented on src/app.py
> +    # [REST/MQTT]
Treba izbaciti ovaj zakomentarisani dio.

2024-02-27 12:37 UTC, sale3 requested changes

2024-02-27 12:57 UTC, sergiPopescou approved these changes

2024-02-27 12:58 UTC, sergiPopescou commented
So proud of this community - meme

2024-02-28 06:46 UTC, sale3 approved these changes

2024-02-28 07:25 UTC, merged