42 can config file upgrade
sale3/iot-gateway-app pull request #55
Opened 2024-02-28 11:21 UTC by CodeBojan

Config file object implementation, with a few quality of life improvements.

2024-02-29 11:02 UTC, sergiPopescou requested changes
__pycache__ ne smije da bude ovdje, ne znam kako je dospio. 
dosta funkcija je prosireno novim parametrima, ali nisu opisani u docstringu
funkcija se importuje iz can_service, ali ista ima definisana ovdje u ovom modulu. tu dolazi do shadowinga!

2024-02-29 11:02 UTC, sergiPopescou commented on src/sensor_devices.py
> +                    init_flags, temp_lock, load_lock, fuel_lock, can_lock):
novi parametri, od init_flags na dalje nisu opisani u docstringu

2024-02-29 11:02 UTC, sergiPopescou commented on src/sensor_devices.py
> +        mqtt_pass,
missing in docstring

2024-03-04 14:31 UTC, stekap000 commented
Nemojte odobravati merge dok se ne provjeri da li se svuda koristi Config klasa i njene metode/svojstva kada se radi sa konfiguracijom.

2024-03-05 07:54 UTC, sergiPopescou submitted a review, later dismissed

2024-03-12 08:28 UTC, sergiPopescou submitted a review, later dismissed

2024-03-12 11:47 UTC, stekap000 approved these changes

2024-03-12 13:25 UTC, sale3 approved these changes

2024-03-12 13:27 UTC, merged