Fixed previous errors, centralized gcb, adapted previous code
sale3/iot-gateway-app pull request #62
Opened 2024-03-13 13:53 UTC by stekap000

Fixed previous errors, centralized gcb, adapted data and stats service to not worry about sending data

2024-03-13 13:55 UTC, stekap000 commented
Docstring i stil ce biti uredjeni kasnije.

2024-03-14 09:30 UTC, sale3 requested changes

2024-03-14 09:30 UTC, sale3 commented on src/sensor_devices.py
> +    #shutdown_thread.start()
Ako nije potrebno, izbaciti. Isto vazi i za join na liniji 841.

2024-03-14 09:30 UTC, sale3 commented on src/rest_api.py
> +            temp['interval'] = config.fuel_settings_interval;
Zbog cega je ovo drugacije od ostalih podataka? Zasto se koristi ovaj temp?

2024-03-14 09:34 UTC, stekap000 commented on src/data_service.py
> +        if value <= limit:  # ASK same limit as his or a different one?
Nisam bio siguran da li da diram jer su od Bojana, ali rekao je da mu ne trebaju vise.

2024-03-14 10:30 UTC, stekap000 commented on src/sensor_devices.py
> +    #shutdown_thread.start()
Moramo odluciti na koji nacin cemo pokretati citav sistem.

2024-03-19 09:33 UTC, sale3 approved these changes

2024-03-19 09:42 UTC, CodeBojan approved these changes

2024-03-19 09:43 UTC, merged