Minor modifications
sale3/iot-gateway-app pull request #68
Opened 2024-04-16 07:48 UTC by CodeBojan

Added a mechanism to detect whether the CAN BUS is receiving messages or not. If it is not receiving messages, the proper console message will be displayed. Added shutdown script and modified exe script slightly.

2024-04-16 09:07 UTC, sale3 requested changes

2024-04-16 09:07 UTC, sale3 commented on src/can_service.py
> +    period_counter = 0
Add a short description of the variable in a comment.

2024-04-16 09:07 UTC, sale3 commented on src/can_service.py
> +    previous_message_counter = 0
Add a short description of the variable in a comment.

2024-04-16 09:07 UTC, sale3 commented on src/can_service.py
> +        self.message_counter = 0
Add a short description of the variable in a comment.

2024-04-16 11:10 UTC, stekap000 commented on src/signal_control.py
> +            if sig > signal.CTRL_BREAK_EVENT:
Given if condition should not be there at all.

2024-04-17 10:26 UTC, sale3 requested changes

2024-04-17 10:26 UTC, sale3 commented on src/can_service.py
> +    period_counter = 0  # if the counter reaches 5, 10 seconds have passed, and then the check is made whether the bus
Looks good, just move the comments above the variable. Same goes for other variables.

2024-04-17 10:27 UTC, stekap000 approved these changes

2024-04-18 07:22 UTC, sale3 approved these changes

2024-04-18 07:28 UTC, stekap000 approved these changes

2024-04-18 07:28 UTC, merged